apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-download"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-download"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["+login", "anonymous", "+force_install_dir", "{{ default "/data" .Values.persistence.data.mountPath }}", "+app_update", "{{ .Values.config.steamAppId }}", "+quit"]
        volumeMounts:
        {{- range $index, $persistence := .Values.persistence }}
        - mountPath: {{ default "/data" $persistence.mountPath }}
          name: {{ default "data" $index }}
        {{- end }}
