# Default values for steamcmd.

image:
  repository: steamcmd/steamcmd
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

init:
  

config:
  # Steam application ID of the game you wish to run.
  # You can use https://steamdb.info to find App IDs
  steamAppId: ""

service:
  port:
    port: 2456
    name: game
  # additionalPorts:
  #   - name: query
  #     port: 2457

persistence:
  config:
    enabled: false
    emptyDir: false

  data:
    enabled: true
    emptyDir: false
    mountPath: /data
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
